services:
  - type: web
    name: newarciicloud
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build:prod
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production