services:
  - type: web
    name: newarciicloud
    env: node
    buildCommand: rm -rf .next && npm install --legacy-peer-deps && npm run build:prod
    startCommand: npm start
    plan: free
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0